/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tela.java
 *
 * Created on 03/04/2009, 21:46:23
 */
package gmail;

import java.security.Security;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;

/**
 *
 * @author Hemerson
 */
public class Tela extends javax.swing.JFrame {

    GmailTest email;

    /** Creates new form Tela */
    public Tela() {
        initComponents();
        this.setLocationRelativeTo(null);
        email = new GmailTest();
        this.logaSistema();
        jTextFieldPara.requestFocus();
    }

    public Tela(String login, String senha) {
        initComponents();
        this.setLocationRelativeTo(null);
        email = new GmailTest();
        email.setLogin(login);
        email.setEmailFromAddress(login);
        jTextFieldDe.setText(login);
        email.setSenha(senha);
        jTextFieldPara.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDe = new javax.swing.JTextField();
        jTextFieldPara = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMensagem = new javax.swing.JTextArea();
        jButtonEnviar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setText("De:");

        jLabel2.setText("Para:");

        jTextFieldDe.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDe.setEditable(false);
        jTextFieldDe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDeFocusLost(evt);
            }
        });

        jTextFieldPara.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPara.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldParaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldParaFocusLost(evt);
            }
        });

        jTextAreaMensagem.setColumns(20);
        jTextAreaMensagem.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMensagem);

        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        jLabel4.setText("Título:");

        jTextFieldTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTituloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTituloFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPara, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addComponent(jTextFieldDe, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnviar))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonEnviar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        if ((jTextFieldDe.getText().equals("")) || (jTextFieldPara.getText().equals("")) || (jTextFieldTitulo.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "E-mail nao pode ser enviado!");
        } else {
            email.setEmailMsgTxt(jTextAreaMensagem.getText());
            Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
            try {
                email.sendSSLMessage(email.getSendTo(), email.getEmailSubjectTxt(), email.getEmailMsgTxt(), email.getEmailFromAddress());
            } catch (MessagingException ex) {
                System.out.println("Erro!");
            }
            System.out.println("Sucessfully Sent mail to All Users");
            JOptionPane.showMessageDialog(null, "E-mail enviado!");
        }
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jTextFieldDeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDeFocusLost
    }//GEN-LAST:event_jTextFieldDeFocusLost

    private void jTextFieldParaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParaFocusLost
        try {
            String str = jTextFieldPara.getText();
            str = str.replace(',', '#');
            String para[] = str.split("#");
            String semEspaco = "";
            for (int i = 0; i < para.length; i++) {
                char a[] = para[i].toCharArray();
                semEspaco = "";
                for (int j = 0; j < a.length; j++) {
                    if (a[j] != ' ') {
                        semEspaco += a[j];
                    }
                }
                para[i] = semEspaco;
            }
            if (para.length > 0) {
                email.setSendTo(para);
            } else {
                jTextFieldPara.setText("ERRO");
            }
        } catch (Exception e) {
            jTextFieldPara.setText("ERRO");
        }

    }//GEN-LAST:event_jTextFieldParaFocusLost

    private void jTextFieldTituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTituloFocusLost
        String str = jTextFieldTitulo.getText();
        if (!str.equals("")) {
            email.setEmailSubjectTxt(str);
        } else {
            jTextFieldTitulo.setText("ERRO");
        }
}//GEN-LAST:event_jTextFieldTituloFocusLost

    private void jTextFieldDeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDeFocusGained
        jTextFieldDe.setSelectionStart(0);
        jTextFieldDe.setSelectionEnd(jTextFieldDe.getText().length());
    }//GEN-LAST:event_jTextFieldDeFocusGained

    private void jTextFieldParaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParaFocusGained
        jTextFieldPara.setSelectionStart(0);
        jTextFieldPara.setSelectionEnd(jTextFieldPara.getText().length());
    }//GEN-LAST:event_jTextFieldParaFocusGained

    private void jTextFieldTituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTituloFocusGained
        jTextFieldTitulo.setSelectionStart(0);
        jTextFieldTitulo.setSelectionEnd(jTextFieldTitulo.getText().length());
    }//GEN-LAST:event_jTextFieldTituloFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Tela().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMensagem;
    private javax.swing.JTextField jTextFieldDe;
    private javax.swing.JTextField jTextFieldPara;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables

    private void logaSistema() {
        String login = JOptionPane.showInputDialog(null, "Login", "Digite seu login");
        if (!login.equals("")) {
            email.setLogin(login);
            email.setEmailFromAddress(login);
            jTextFieldDe.setText(login);
            String senha = JOptionPane.showInputDialog(null, "Senha", "Digite sua senha");
            if (!senha.equals("")) {
                email.setSenha(senha);
            } else {
                System.exit(0);
            }
        } else {
            System.exit(0);
        }
    }
}
